name: ignorolo

on:
  push:
    branches:
      - chida

jobs:
  primis:
    name: El primero
    runs-on: ubuntu-latest
    steps:
      - name: Tranquilos va empezando
        uses: actions/checkout@master
      - name: Agarrence que lleva bala
        run: git merge master
      - name: Les va
        run: git push "https://${{github.actor}}:${{github.token}}@github.com/${{github.repository}}.git" HEAD:master

  seguns:
    name: El segundo
    runs-on: ubuntu-latest
    needs: primis
    steps:
      - name: Ya termino mergas
        run: echo "Fin"